# Generated by Django 4.2.7 on 2026-04-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_swaprequest_milestone_swapmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='receiver_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='sender_completed',
            field=models.BooleanField(default=False),
        ),
    ]
